export enum ReportPermissions
{
    MANAGERS_MEMBERS_KANBAN = 'REPORT_KANBAN_PROJECT_MANAGER_AND_MEMBER',
    MANAGERS_MEMBERS_TRELLO = 'REPORT_TRELLO_PROJECT_MANAGER_AND_MEMBER',
    USER_KANBAN_TRELLO = 'REPORT_KANBAN_TRELLO_PROJECT_WITH_USER',
    CHART_KANBAN = 'REPORT_CHART_KANBAN_PROJECT',
    CHART_TRELLO = 'REPORT_CHART_TRELLO_PROJECT',
    TIME_LEFT = 'REPORT_TIME_LEFT',
    MANAGERS_MEMBERS_UPLOAD = 'REPORT_MANAGERS_MEMBERS_UPLOAD',
    USER_UPLOAD = 'REPORT_PERSONAL_UPLOAD',
    TIME_LEFT_UPLOAD = 'REPORT_TIME_LEFT_UPLOAD',
}