export enum ProjectPermissions
{
    CREATE = 'PROJECT_CREATE',
    READ = 'PROJECT_READ',
    UPDATE = 'PROJECT_UPDATE',
    DELETE = 'PROJECT_DELETE',
    CHANGE_BACKGROUND = 'PROJECT_CHANGE_BACKGROUND',
    READ_DETAILS = 'PROJECT_READ_DETAILS',
}