export enum EmployeePermissions
{
    CREATE = 'EMPLOYEE_CREATE',
    READ = 'EMPLOYEE_READ',
    UPDATE = 'EMPLOYEE_UPDATE',
    DELETE = 'EMPLOYEE_DELETE',
    CHANGE_PASSWORD = 'EMPLOYEE_CHANGE_PASSWORD',
}