export enum UserPermissions
{
    GET_ME = 'USER_GET_ME',
    ATTACH_ROLE = 'USER_ATTACH_ROLE',
    CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
    CHANGE_LANGUAGE = 'USER_CHANGE_LANGUAGE',
    UPDATE_PROFILE = 'USER_UPDATE_PROFILE',
}