export enum ProjectColumnPermissions
{
    CREATE = 'PROJECT_COLUMN_CREATE',
    READ = 'PROJECT_COLUMN_READ',
    UPDATE = 'PROJECT_COLUMN_UPDATE',
    DELETE = 'PROJECT_COLUMN_DELETE',
    MOVE = 'PROJECT_COLUMN_MOVE',
}